name: hyper-stylize
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.8.0
  - pytorch-cuda=12.1
  - torchvision
  - pip
  - pip:
      - insightface==0.7.3
      - face_recognition==1.3.0
      - opencv-python-headless==4.10.0.84
      - pillow==10.4.0
      - requests==2.32.3
      - python-dotenv==1.0.1
      - numpy==1.26.4

