models:
  epicrealism_xl:
    name: epiCRealism XL (VXVII - CrystalClear)
    path: models/epiCRealismXL_VXVII_CrystalClear.safetensors
    model_page: https://civitai.com/models/277058
    download_url: https://civitai.com/api/download/models/1920523?type=Model&format=SafeTensor
    alternative_urls:
      - https://civitai.com/api/download/models/489217?type=Model&format=SafeTensor  # V7-Final Destination
      - https://civitai.com/api/download/models/956266?type=Model&format=SafeTensor  # VXVI-LastFAME fallback
    description: Top-tier photorealism SDXL checkpoint by epinikion; extremely detailed skin, lighting, micro‑expressions (latest CrystalClear version)
    recommended_cfg: 5‑7
    recommended_steps: 25‑40
    sampler: "DPM++ 2M Karras"
    strength: 0.4
    hires_fix: true
    hires_upscaler: "4x-UltraSharp"
    hires_steps: 20
    speciality: "photorealistic_portraits"
    file_size: "6.46 GB"

  realvisxl_v5_lightning:
    name: RealVisXL V5.0 Lightning
    path: models/RealVisXL_V5_Lightning.safetensors
    model_page: https://civitai.com/models/139562
    download_url: https://civitai.com/api/download/models/798204?type=Model&format=SafeTensor
    alternative_urls:
      - https://huggingface.co/SG161222/RealVisXL_V4.0/resolve/main/RealVisXL_V4.0.safetensors  # V4.0 fallback
    description: Cinematic portrait‑focused SDXL model optimized for face anatomy, soft edges, expressive realism (Lightning version)
    recommended_cfg: 1.5
    recommended_steps: 5‑30
    sampler: "DPM++ SDE Karras"
    strength: 0.3
    hires_fix: true
    hires_upscaler: "ESRGAN_4x"
    hires_steps: 15
    speciality: "fast_lightning_generation"
    file_size: "6.46 GB"

  juggernaut_xl_v9:
    name: Juggernaut XL v9 (RunDiffusion)
    path: models/Juggernaut_XL_v9.safetensors
    model_page: https://huggingface.co/RunDiffusion/Juggernaut-XL-v9
    download_url: https://huggingface.co/RunDiffusion/Juggernaut-XL-v9/resolve/main/Juggernaut_XL_v9.safetensors
    alternative_urls:
      - https://civitai.com/api/download/models/456194?type=Model&format=SafeTensor  # CivitAI backup
    description: Versatile and highly realistic SDXL checkpoint (v9) with photographic lighting, skin detail, environment fidelity
    recommended_cfg: 3‑7
    recommended_steps: 30‑40
    sampler: "DPM++ 2M Karras"
    strength: 0.4
    hires_fix: true
    hires_upscaler: "4x-UltraSharp"
    hires_steps: 25
    speciality: "versatile_realism"
    file_size: "6.62 GB"

  realism_engine_sdxl:
    name: Realism Engine SDXL v3.0
    path: models/RealismEngine_SDXL_v30.safetensors
    model_page: https://civitai.com/models/152525
    download_url: https://civitai.com/api/download/models/336875?type=Model&format=SafeTensor
    description: Ultra-realistic SDXL model specialized in photographic quality, skin textures, and natural lighting
    recommended_cfg: 7‑9
    recommended_steps: 30‑50
    sampler: "DPM++ SDE Karras"
    strength: 0.5
    hires_fix: true
    hires_upscaler: "4x-UltraSharp"
    hires_steps: 30
    speciality: "ultra_realism"
    file_size: "6.62 GB"

  albedobase_xl:
    name: AlbedoBase XL v2.1
    path: models/AlbedoBase_XL_v21.safetensors
    model_page: https://civitai.com/models/140737
    download_url: https://civitai.com/api/download/models/281176?type=Model&format=SafeTensor
    description: High-quality SDXL base model with excellent skin rendering and natural color reproduction
    recommended_cfg: 6‑8
    recommended_steps: 25‑35
    sampler: "DPM++ 2M Karras"
    strength: 0.4
    hires_fix: true
    hires_upscaler: "ESRGAN_4x"
    hires_steps: 20
    speciality: "natural_skin_tones"
    file_size: "6.62 GB"

  dreamshaper_xl:
    name: DreamShaper XL v2.1
    path: models/DreamShaper_XL_v21.safetensors
    model_page: https://civitai.com/models/112902
    download_url: https://civitai.com/api/download/models/251662?type=Model&format=SafeTensor
    description: Well-balanced SDXL model for realistic portraits with artistic flair
    recommended_cfg: 5‑7
    recommended_steps: 20‑30
    sampler: "DPM++ 2M Karras"
    strength: 0.35
    hires_fix: true
    hires_upscaler: "4x-UltraSharp"
    hires_steps: 20
    speciality: "artistic_realism"
    file_size: "6.46 GB"

  copax_realistic_xl:
    name: Copax Realistic XL v5.0
    path: models/Copax_Realistic_XL_v50.safetensors
    model_page: https://civitai.com/models/130090
    download_url: https://civitai.com/api/download/models/307905?type=Model&format=SafeTensor
    description: Ultra-realistic SDXL model optimized for portrait photography and character realism
    recommended_cfg: 6‑8
    recommended_steps: 25‑35
    sampler: "DPM++ SDE Karras"
    strength: 0.4
    hires_fix: true
    hires_upscaler: "4x-UltraSharp"
    hires_steps: 25
    speciality: "portrait_realism"
    file_size: "6.62 GB"

  proteus_xl:
    name: Proteus XL v0.4
    path: models/Proteus_XL_v04.safetensors
    model_page: https://civitai.com/models/120919
    download_url: https://civitai.com/api/download/models/288982?type=Model&format=SafeTensor
    description: Advanced SDXL model with exceptional detail and photorealism for character faces
    recommended_cfg: 7‑9
    recommended_steps: 30‑40
    sampler: "DPM++ 2M Karras"
    strength: 0.45
    hires_fix: true
    hires_upscaler: "ESRGAN_4x"
    hires_steps: 30
    speciality: "detail_realism"
    file_size: "6.62 GB"

  newreality_xl:
    name: NewReality XL v2.0
    path: models/NewReality_XL_v20.safetensors
    model_page: https://civitai.com/models/161068
    download_url: https://civitai.com/api/download/models/384264?type=Model&format=SafeTensor
    description: Cutting-edge photorealistic SDXL model specialized in facial details and skin textures
    recommended_cfg: 5‑7
    recommended_steps: 25‑35
    sampler: "DPM++ SDE Karras" 
    strength: 0.4
    hires_fix: true
    hires_upscaler: "4x-UltraSharp"
    hires_steps: 25
    speciality: "skin_detail"
    file_size: "6.46 GB"

# ADetailer face detection models
adetailer_models:
  face_yolov8n:
    name: "YOLOv8n Face Detection"
    model_file: "face_yolov8n.pt"
    download_url: "https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8n.pt"
    description: "Fast and accurate face detection model"
    confidence_threshold: 0.3
    speed: "very_fast"
    accuracy: "good"

  face_yolov8s:
    name: "YOLOv8s Face Detection"
    model_file: "face_yolov8s.pt"
    download_url: "https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8s.pt"
    description: "Balanced speed/accuracy face detection"
    confidence_threshold: 0.3
    speed: "fast"
    accuracy: "very_good"

  face_yolov8m:
    name: "YOLOv8m Face Detection"
    model_file: "face_yolov8m.pt"
    download_url: "https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8m.pt"
    description: "High accuracy face detection model"
    confidence_threshold: 0.3
    speed: "medium"
    accuracy: "excellent"

  face_yolov8l:
    name: "YOLOv8l Face Detection"
    model_file: "face_yolov8l.pt"
    download_url: "https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8l.pt"
    description: "Large model for maximum accuracy"
    confidence_threshold: 0.25
    speed: "slow"
    accuracy: "superior"

  face_yolov8x:
    name: "YOLOv8x Face Detection"
    model_file: "face_yolov8x.pt"
    download_url: "https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8x.pt"
    description: "Extra large model for professional use"
    confidence_threshold: 0.25
    speed: "very_slow"
    accuracy: "ultimate"

  mediapipe_face:
    name: "MediaPipe Face Detection"
    model_file: "mediapipe_face_detection"
    description: "Google MediaPipe face detection"
    confidence_threshold: 0.5
    speed: "very_fast"
    accuracy: "good"
    
  hand_yolov8n:
    name: "YOLOv8n Hand Detection"
    model_file: "hand_yolov8n.pt"
    download_url: "https://huggingface.co/Bingsu/adetailer/resolve/main/hand_yolov8n.pt"
    description: "Hand detection for fixing hand artifacts"
    confidence_threshold: 0.3

# Upscaler models
upscaler_models:
  esrgan_4x:
    name: "ESRGAN 4x"
    path: "models/ESRGAN/ESRGAN_4x.pth"
    download_url: "https://github.com/xinntao/ESRGAN/releases/download/v0.0.0/ESRGAN_4x.pth"
    description: "General purpose 4x upscaler"

  ultrasharp_4x:
    name: "4x-UltraSharp"
    path: "models/ESRGAN/4x-UltraSharp.pth"
    download_url: "https://mega.nz/file/qZRBmaIY#nIG8KyWFcGNTuMX_XNbJ_TaxQX_ckACh8kxOxnwQKhX"
    description: "Ultra-sharp 4x upscaler for detailed images"

# Model categories for easy selection
categories:
  photorealism:
    - epicrealism_xl
    - realism_engine_sdxl
    - juggernaut_xl_v9
    - copax_realistic_xl
    - proteus_xl
    - newreality_xl
  
  fast_generation:
    - realvisxl_v5_lightning
    - dreamshaper_xl
  
  skin_specialists:
    - albedobase_xl
    - epicrealism_xl
    - realism_engine_sdxl
    - newreality_xl
    - copax_realistic_xl
  
  portrait_specialists:
    - copax_realistic_xl
    - proteus_xl
    - epicrealism_xl
    - newreality_xl
  
  detail_specialists:
    - proteus_xl
    - realism_engine_sdxl
    - juggernaut_xl_v9
  
  versatile:
    - juggernaut_xl_v9
    - dreamshaper_xl
    - albedobase_xl

# Face detection model recommendations
face_detection_presets:
  fast_preview:
    model: "face_yolov8n"
    confidence: 0.3
    description: "Fast preview processing"
    
  balanced_quality:
    model: "face_yolov8s"
    confidence: 0.3
    description: "Good balance of speed and accuracy"
    
  high_accuracy:
    model: "face_yolov8m"
    confidence: 0.3
    description: "High accuracy for production use"
    
  maximum_quality:
    model: "face_yolov8l"
    confidence: 0.25
    description: "Maximum accuracy for professional work"
    
  ultra_precision:
    model: "face_yolov8x"
    confidence: 0.25
    description: "Ultimate precision for critical applications"
